version: 1

reviews:

  auto_review:
    enabled: true

    auto_incremental_review: true

    branches:
      include:
        - main
        - develop
        - release/**
        - feature/**
        - infra/**
        - architecture/**
        - engine/**
        - runtime/**

      exclude:
        - spike/**
        - experiment/**
        - hotfix/**
        - temp/**

    paths:
      include:
        - app/runtime/**
        - app/engine/**
        - app/domain/**
        - app/infra/**
        - "**/lib/**"
        - "**/types/**"
        - "**/constants/**"
        - "**/database/**"


      exclude:
        - app/ui/**
        - app/components/**
        - app/styles/**
        - "**/ui/**"
        - "**/components/**"
        - "**/styles/**"
        - "**/*.md"
        - "**/*.stories.*"
        - "**/*.test.*"

    focus:
      - correctness
      - architecture
      - performance
      - security
      - maintainability

    tone:
      strict: true
      verbosity: concise
      suggestions_only: false

      chat:
        enabled: true
        model: gpt-4
        knowledge_base:
        opt_out: false
        learnings:
          scope: auto
        issues:
          scope: auto